- name: "Configure backend server"
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: "Set environment variables"
  shell: |
    export TYPEORM_MIGRATIONS_DIR="${TYPEORM_CONNECTION}" 
    export TYPEORM_DATABASE="UdaPeopleDB"

- name: "Install Node.js 13"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo npm install -g n
    sudo n 13.8.0

- name: "Install PM2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

